language: ruby
rvm:
  - 2.0.0-p247
install:
- gem install bundler
- bundle install
before_script:
- "export PHANTOMJS_EXECUTABLE='phantomjs --local-to-remote-url-access=yes --ignore-ssl-errors=yes'"
script:
- bundle exec cucumber features BROWSER=phantomjs

